interface IRegistration { //request to the server from front
  login: string,
  name: string,
  password: string,
  email?: string,
}

interface ILogin { //request to the server from front
  login: string,
  password: string,
}

interface IPost { // description of the post in feed, request to the server from front
  author: IUser,
  date: Date, //on the server side
  headline: string,
  text: string,
  images: string[],
  likes: ILike[],
  comments: IMessage[],
}

interface IUser { //data base
  _id: string, //generated by MongoDB
  name: string,
  password: string,
  avatar: string,
  lastVisited?: Date,
  isOnline: boolean, //default state is false
  subscribers: IUser[], // array of user's IDs,
  gallery: IPhoto[], //array of links of photos
  posts: IPost[], //links to user's posts
  chats: IChat[], //array of links of chats
}

type Feed = IPost[];
type SUbscribers = IUser[];

interface IPhoto {
  _id: string, //generated by MongoDB
  author: IUser,
  photo: string,
  likes: number,
  date: Date,
}

interface IChat {
  _id: string,
  users: [IUser, IUser],
  messages: IMessage[],  
}

interface IMessage {
  _id: string,
  date: Date,
  content: string,
  author: IUser,  
}

interface ILike {
  _id: string,
  author: IUser,
  object: IPost | IPhoto,
}




